# Generated by Django 6.1.1 on 2026-09-27 03:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_reference', models.CharField(db_index=True, help_text='Campaign/brand owner this asset belongs to. Will become a Campaign FK once that model exists.', max_length=255)),
                ('original_url', models.URLField(max_length=2000)),
                ('stored_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source', models.CharField(blank=True, help_text="e.g. 'website_snapshot', 'reference_upload'.", max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('temporary', 'Temporary'), ('persistent', 'Persistent'), ('failed', 'Failed'), ('unusable', 'Unusable')], default='pending', max_length=20)),
                ('storage_provider', models.CharField(blank=True, help_text="e.g. 'local', 's3'. Empty until stored somewhere.", max_length=50)),
                ('provenance_notes', models.TextField(blank=True, help_text='Free-text: which page/snapshot this came from, extraction confidence, why it failed, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When set, a temporary asset eligible for cleanup after this time.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
